# Generated by Django 5.1.2 on 2024-10-27 14:39

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime.now,
                null=True,
                verbose_name="Время последнего посещения",
            ),
        ),
    ]
