# Generated by Django 5.1.2 on 2024-11-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_last_login"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="cost",
            new_name="amount",
        ),
    ]
