# Generated by Django 5.1.2 on 2024-10-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["title"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course", "title"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="title",
        ),
    ]
