# Generated by Django 5.1.2 on 2024-10-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0002_alter_course_options_alter_lesson_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Video URL",
                null=True,
                verbose_name="ссылка на урок",
            ),
        ),
    ]
